# GitHub will render a "Sponsor" button on the repo using this config.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: lintuxt
